### ISSUE TITLE
Question about inference

### ISSUE THREAD

**Issue by Iceeteeea** [ToTheBeginning/GCP-Colorization#7]
`/home/fzh/.conda/envs/video/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/fzh/.conda/envs/video/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  warn(f"Failed to load image Python extension: {e}")
Cannot import deform_conv_ext. You can ignore this message if you are using torchvision >= 0.9.0.
Otherwise you may need to check whether the DCN has been successfully installed.
Adding attention layer in D at resolution 64
Adding attention layer in E at resolution 64
Adding attention layer in G at resolution 64
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    main()
  File "main.py", line 28, in main
    sol.run()
  File "/home/fzh/workspace/GCP-Colorization/solvers/base_solver.py", line 29, in run
    self.test()
  File "/home/fzh/workspace/GCP-Colorization/solvers/refcolor_solver.py", line 67, in test
    self.test_dl = data.get_loader(cfg=self.cfg, ds=self.cfg.DATA.NAME)
  File "/home/fzh/workspace/GCP-Colorization/data/__init__.py", line 21, in get_loader
    dataset = dataset_cls(cfg)
  File "/home/fzh/workspace/GCP-Colorization/data/imagenet_inference.py", line 99, in __init__
    assert img_name in label_map
AssertionError
`

**Comment by ToTheBeginning** [comment]
Hi, if you are testing in-the-wild images, this AssertionError indicates that `assets/predicted_label_for_user_image.txt ` file doesn't contain the predicted label for your testing images. Please check the instruction [here](https://github.com/ToTheBeginning/GCP-Colorization#test-in-the-wild-images).


<img width="835" alt="image" src="https://user-images.githubusercontent.com/11482921/233816129-eca3ab34-9941-42cf-afec-47a3213f4f46.png">
